use crate::error::CmdError;
use fs_extra::file::write_all;
use function_name::named;
use scoretracker::data::games::registered_games;
use scoretracker::util::relative_path_from_segments;
use scoretracker::{error, info, log_fn_name, success, success_npr};
use std::fs;
use std::io::ErrorKind;
use std::path::PathBuf;
use std::process::Command;

pub const SCHEMAS_DIR: &[&str] = &["gen", "schemas"];
pub fn schemas_dir_path() -> PathBuf {
    relative_path_from_segments(SCHEMAS_DIR).to_path(".")
}

pub const TYPES_DIR: &[&str] = &["web-frontend", "static", "ts", "gen", "types"];
pub fn types_dir_path() -> PathBuf {
    relative_path_from_segments(TYPES_DIR).to_path(".")
}

pub fn gen_full() -> Result<(), CmdError> {
    gen_json()?;
    gen_types()?;
    Ok(())
}

#[named]
pub fn gen_json() -> Result<(), CmdError> {
    log_fn_name!(auto);
    info!("generating json schemas from rust types");

    let dir = schemas_dir_path();
    fs::create_dir_all(&dir).expect("could not create dir for schemas");

    for (name, schema) in registered_games().iter().map(|game| (game.schema_name(), game.schema())) {
        let schema_str = serde_json::to_string_pretty(&schema)
            .unwrap_or_else(|e| panic!("could not serialize schema '{name}'; reason: {e}; schema: {schema:?}"));
        let path = dir.join(format!("{name}.schema.json"));
        write_all(&path, &schema_str).unwrap_or_else(|e| panic!("could not write schema '{name}' to file: {path:?}; reason: {e}"));
        success!("json schema written to {path:?}");
    }
    Ok(())
}

#[named]
pub fn gen_types() -> Result<(), CmdError> {
    log_fn_name!(auto);
    info!("generating typescript .d.ts files from json schemas");

    #[cfg(target_family = "windows")]
    const NPX_EXECUTABLE_NAME: &str = "npx.cmd";
    #[cfg(target_family = "unix")]
    const NPX_EXECUTABLE_NAME: &str = "npx";

    const BANNER_COMMENT: &str = r"/* eslint-disable */
        /**
         * This file was automatically generated by json-schema-to-typescript.
         * DO NOT MODIFY IT BY HAND - any changes will be overwritten.
         * Instead, modify the source code for the types in Rust, and then execute
         * the command: `cargo run schema gen` in the root directory of the project
         * to regenerate this file.
         */";

    #[cfg(target_family = "windows")]
    // batch files are not allowed to have newlines in cmdline parameters i think...?
    // TODO: maybe this can be fixed in a better way
    let banner_comment = BANNER_COMMENT.replace("\n", " ");
    #[cfg(target_family = "unix")]
    let banner_comment = BANNER_COMMENT;

    let input_dir = schemas_dir_path().to_string_lossy().to_string();
    let output_dir = types_dir_path().to_string_lossy().to_string();
    info!("generated files will be written to: {:?}", types_dir_path());

    let out = Command::new(NPX_EXECUTABLE_NAME)
        .arg("json2ts")
        .arg("-i")
        .arg(input_dir)
        .arg("-o")
        .arg(output_dir)
        .arg("--no-additionalProperties")
        // .arg("--unreachableDefinitions")
        .arg("--bannerComment")
        .arg(banner_comment)
        .output()
        .expect("json2ts error:");
    info!("captured stdout: {}", String::from_utf8_lossy(&out.stdout));
    info!("captured stderr: {}", String::from_utf8_lossy(&out.stderr));

    if out.status.success() {
        success!("process json2ts finished successfully: {}", out.status)
    } else {
        error!("process json2ts failed: {}", out.status)
    }

    Ok(())
}

pub fn clean() -> Result<(), CmdError> {
    let path1 = schemas_dir_path();
    fs::remove_dir_all(&path1).unwrap_or_else(|e| match e.kind() {
        ErrorKind::NotFound => {}
        _ => {
            panic!("could not remove directory: {path1:?}, reason: {e}");
        }
    });
    let path2 = types_dir_path();
    fs::remove_dir_all(&path2).unwrap_or_else(|e| match e.kind() {
        ErrorKind::NotFound => {}
        _ => {
            panic!("could not remove directory: {path2:?}, reason: {e}");
        }
    });
    success_npr!("deleted {path1:?} and {path2:?} directories");
    Ok(())
}
