use std::fs;
use std::path::PathBuf;
use std::process::Command;

use crate::error::CmdError;
use fs_extra::file::write_all;
use schemars::schema_for;
use scoretracker::data::games::{adofai, arcaea};
use scoretracker::util::relative_path_from_segments;
use scoretracker::{error, info, log_fn_name, success};

pub const SCHEMAS_DIR: &[&str] = &["gen", "schemas"];
pub fn schemas_dir_path() -> PathBuf {
    relative_path_from_segments(SCHEMAS_DIR).to_path(".")
}

pub const TYPES_DIR: &[&str] = &["web-frontend", "static", "ts", "gen", "types"];
pub fn types_dir_path() -> PathBuf {
    relative_path_from_segments(TYPES_DIR).to_path(".")
}

pub fn gen_full() -> Result<(), CmdError> {
    gen_json()?;
    gen_types()?;
    Ok(())
}

pub fn gen_json() -> Result<(), CmdError> {
    log_fn_name!("gen_json");
    info!("generating json schemas from rust types");

    let dir = schemas_dir_path();
    fs::create_dir_all(&dir).expect("could not create dir for schemas");

    let schema = schema_for!(adofai::Performance);
    let schema_str = serde_json::to_string_pretty(&schema).unwrap();
    let path = dir.join("adofai.schema.json");
    write_all(&path, &schema_str).expect("could not write to file");
    success!("json schema written to {path:?}");

    let schema = schema_for!(arcaea::Performance);
    let schema_str = serde_json::to_string_pretty(&schema).unwrap();
    let path = dir.join("arcaea.schema.json");
    write_all(&path, &schema_str).expect("could not write to file");
    success!("json schema written to {path:?}");
    Ok(())
}

pub fn gen_types() -> Result<(), CmdError> {
    log_fn_name!("gen_types");
    info!("generating typescript .d.ts files from json schemas");

    let input_dir = schemas_dir_path().to_string_lossy().to_string();
    let output_dir = types_dir_path().to_string_lossy().to_string();

    let out = Command::new("npx")
        .arg("json2ts")
        .arg("-i")
        .arg(input_dir)
        .arg("-o")
        .arg(output_dir)
        .arg("--bannerComment")
        .arg(
            r"/* eslint-disable */
        /**
         * This file was automatically generated by json-schema-to-typescript.
         * DO NOT MODIFY IT BY HAND - any changes will be overwritten.
         * Instead, modify the source code for the types in Rust, and then execute
         * the command: `cargo run schema gen` in the root directory of the project
         * to regenerate this file.
         */",
        )
        .output()
        .expect("json2ts error:");
    info!("captured stdout: {}", String::from_utf8_lossy(&out.stdout));
    info!("captured stderr: {}", String::from_utf8_lossy(&out.stderr));

    if out.status.success() {
        success!("process json2ts finished successfully: {}", out.status)
    } else {
        error!("process json2ts failed: {}", out.status)
    }

    Ok(())
}
